### ISSUE TITLE
mysql_user stops working in MariaDB 10.6.12

### ISSUE THREAD

**Issue by tangel0v** [ansible-collections/ansible.mysql#566]
##### SUMMARY
mysql_user module stops working after upgrading MariaDB to 10.6 version.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mysql_user

##### ANSIBLE VERSION
```
ansible [core 2.15.2]
  config file = None
  configured module search path = ['/home/tangel0v/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/tangel0v/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/tangel0v/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/tangel0v/.local/bin/ansible
  python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION
```
ansible-galaxy collection list community.mysql

# /home/tangel0v/.ansible/collections/ansible_collections
Collection      Version
--------------- -------
community.mysql 3.7.2  

# /home/tangel0v/.local/lib/python3.10/site-packages/ansible_collections
Collection      Version
--------------- -------
community.mysql 3.7.2 
```

##### CONFIGURATION
```paste below
ansible-config dump --only-changed
CONFIG_FILE() = None
PAGER(env: PAGER) = less
```

##### OS / ENVIRONMENT
OS versions: Ubuntu 22.04.2 and Ubuntu 22.04.3
Architecture: aarch64
Linux Kernel:  5.15
Python 3.10

Extra information:
I've tried it with the following packages:
- mysqlclient 2.1.0 installed with pip
- python3-pymysql installed with apt
- pymysql 1.1.0 installed with pip

No success with any alternative.

I think it's related to these errors:
-  https://github.com/eslam-gomaa/mysql_secure_installation_Ansible/issues/11
- https://stackoverflow.com/questions/64841185/error-1356-hy000-view-mysql-user-references-invalid-tables-or-columns-o

The user used to test has root access to the MariaDB server and it works if you use MySQL commands (to verify if it's a lack of permissions or not)

##### STEPS TO REPRODUCE
Just try to update the password or any permissions of an already created user.
```yaml
    - name: Creating Wordpress user
      community.mysql.mysql_user:
        user: "{{ wordpress_mysql_user }}"
        password: "{{ wordpress_mysql_user_password }}"
        priv: "{{ wordpress_mysql_database }}.*:ALL"
        state: present
        login_user: root
        login_password: "{{ mysql_root_user_password }}"
        login_unix_socket: /run/mysqld/mysqld.sock
```

##### EXPECTED RESULTS
The task is not changed if the password is the same or it's changed if one of the parameters in mysql_user modifies the MySQL user.

##### ACTUAL RESULTS
```
TASK [Creating Wordpress user] ************************************************************************************************************************************************
task path: /home/tangel0v/Developments/own-config/playbooks/tasks/mysql.yml:24
Using module file /home/tangel0v/.ansible/collections/ansible_collections/community/mysql/plugins/modules/mysql_user.py
Pipelining is enabled.
<private-ip> ESTABLISH SSH CONNECTION FOR USER: nanananabatman
<private-ip> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="nanananabatman"' -o ConnectTimeout=10 -o 'ControlPath="/home/tangel0v/.ansible/cp/51f90cca8f"' private-ip '/bin/sh -c '"'"'sudo -H -S -p "[sudo via ansible, key=notapublicone] password:" -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-not-a-public-one ; /usr/bin/python3'"'"'"'"'"'"'"'"' && sleep 0'"'"''
Escalation succeeded
<private-ip> (1, b'', b'Traceback (most recent call last):\n  File "<stdin>", line 107, in <module>\n  File "<stdin>", line 99, in _ansiballz_main\n  File "<stdin>", line 47, in invoke_module\n  File "/usr/lib/python3.10/runpy.py", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code\n    exec(code, run_globals)\n  File "/tmp/ansible_community.mysql.mysql_user_payload_glhczqhm/ansible_community.mysql.mysql_user_payload.zip/ansible_collections/community/mysql/plugins/modules/mysql_user.py", line 528, in <module>\n  File "/tmp/ansible_community.mysql.mysql_user_payload_glhczqhm/ansible_community.mysql.mysql_user_payload.zip/ansible_collections/community/mysql/plugins/modules/mysql_user.py", line 518, in main\n  File "/tmp/ansible_community.mysql.mysql_user_payload_glhczqhm/ansible_community.mysql.mysql_user_payload.zip/ansible_collections/community/mysql/plugins/module_utils/user.py", line 41, in user_exists\n  File "/usr/local/lib/python3.10/dist-packages/pymysql/cursors.py", line 153, in execute\n    result = self._query(query)\n  File "/usr/local/lib/python3.10/dist-packages/pymysql/cursors.py", line 322, in _query\n    conn.query(q)\n  File "/usr/local/lib/python3.10/dist-packages/pymysql/connections.py", line 558, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n  File "/usr/local/lib/python3.10/dist-packages/pymysql/connections.py", line 822, in _read_query_result\n    result.read()\n  File "/usr/local/lib/python3.10/dist-packages/pymysql/connections.py", line 1200, in read\n    first_packet = self.connection._read_packet()\n  File "/usr/local/lib/python3.10/dist-packages/pymysql/connections.py", line 772, in _read_packet\n    packet.raise_for_error()\n  File "/usr/local/lib/python3.10/dist-packages/pymysql/protocol.py", line 221, in raise_for_error\n    err.raise_mysql_exception(self._data)\n  File "/usr/local/lib/python3.10/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception\n    raise errorclass(errno, errval)\npymysql.err.OperationalError: (1356, "View \'mysql.user\' references invalid table(s) or column(s) or function(s) or definer/invoker of view lack rights to use them")\n')
<private-ip> Failed to connect to the host via ssh: Traceback (most recent call last):
  File "<stdin>", line 107, in <module>
  File "<stdin>", line 99, in _ansiballz_main
  File "<stdin>", line 47, in invoke_module
  File "/usr/lib/python3.10/runpy.py", line 224, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_community.mysql.mysql_user_payload_glhczqhm/ansible_community.mysql.mysql_user_payload.zip/ansible_collections/community/mysql/plugins/modules/mysql_user.py", line 528, in <module>
  File "/tmp/ansible_community.mysql.mysql_user_payload_glhczqhm/ansible_community.mysql.mysql_user_payload.zip/ansible_collections/community/mysql/plugins/modules/mysql_user.py", line 518, in main
  File "/tmp/ansible_community.mysql.mysql_user_payload_glhczqhm/ansible_community.mysql.mysql_user_payload.zip/ansible_collections/community/mysql/plugins/module_utils/user.py", line 41, in user_exists
  File "/usr/local/lib/python3.10/dist-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.10/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.10/dist-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.10/dist-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.10/dist-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.10/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.10/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.10/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1356, "View 'mysql.user' references invalid table(s) or column(s) or function(s) or definer/invoker of view lack rights to use them")
The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 107, in <module>
  File "<stdin>", line 99, in _ansiballz_main
  File "<stdin>", line 47, in invoke_module
  File "/usr/lib/python3.10/runpy.py", line 224, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_community.mysql.mysql_user_payload_glhczqhm/ansible_community.mysql.mysql_user_payload.zip/ansible_collections/community/mysql/plugins/modules/mysql_user.py", line 528, in <module>
  File "/tmp/ansible_community.mysql.mysql_user_payload_glhczqhm/ansible_community.mysql.mysql_user_payload.zip/ansible_collections/community/mysql/plugins/modules/mysql_user.py", line 518, in main
  File "/tmp/ansible_community.mysql.mysql_user_payload_glhczqhm/ansible_community.mysql.mysql_user_payload.zip/ansible_collections/community/mysql/plugins/module_utils/user.py", line 41, in user_exists
  File "/usr/local/lib/python3.10/dist-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.10/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.10/dist-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.10/dist-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.10/dist-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.10/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.10/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.10/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1356, "View 'mysql.user' references invalid table(s) or column(s) or function(s) or definer/invoker of view lack rights to use them")
fatal: [wordpress]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 107, in <module>\n  File \"<stdin>\", line 99, in _ansiballz_main\n  File \"<stdin>\", line 47, in invoke_module\n  File \"/usr/lib/python3.10/runpy.py\", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_community.mysql.mysql_user_payload_glhczqhm/ansible_community.mysql.mysql_user_payload.zip/ansible_collections/community/mysql/plugins/modules/mysql_user.py\", line 528, in <module>\n  File \"/tmp/ansible_community.mysql.mysql_user_payload_glhczqhm/ansible_community.mysql.mysql_user_payload.zip/ansible_collections/community/mysql/plugins/modules/mysql_user.py\", line 518, in main\n  File \"/tmp/ansible_community.mysql.mysql_user_payload_glhczqhm/ansible_community.mysql.mysql_user_payload.zip/ansible_collections/community/mysql/plugins/module_utils/user.py\", line 41, in user_exists\n  File \"/usr/local/lib/python3.10/dist-packages/pymysql/cursors.py\", line 153, in execute\n    result = self._query(query)\n  File \"/usr/local/lib/python3.10/dist-packages/pymysql/cursors.py\", line 322, in _query\n    conn.query(q)\n  File \"/usr/local/lib/python3.10/dist-packages/pymysql/connections.py\", line 558, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n  File \"/usr/local/lib/python3.10/dist-packages/pymysql/connections.py\", line 822, in _read_query_result\n    result.read()\n  File \"/usr/local/lib/python3.10/dist-packages/pymysql/connections.py\", line 1200, in read\n    first_packet = self.connection._read_packet()\n  File \"/usr/local/lib/python3.10/dist-packages/pymysql/connections.py\", line 772, in _read_packet\n    packet.raise_for_error()\n  File \"/usr/local/lib/python3.10/dist-packages/pymysql/protocol.py\", line 221, in raise_for_error\n    err.raise_mysql_exception(self._data)\n  File \"/usr/local/lib/python3.10/dist-packages/pymysql/err.py\", line 143, in raise_mysql_exception\n    raise errorclass(errno, errval)\npymysql.err.OperationalError: (1356, \"View 'mysql.user' references invalid table(s) or column(s) or function(s) or definer/invoker of view lack rights to use them\")\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by tangel0v** [comment]
Hello, after some research I am going to close this task. I've been debugging the root cause and I've found that some views in my installation where corrupted, causing the account not to be able to see its own permissions.

For example:
```
REPAIR VIEW sys.host_summary_by_file_io;
REPAIR VIEW sys.host_summary_by_file_io_type;
REPAIR VIEW sys.host_summary_by_stages;
```

I'll put the comment here to help other people in the future and sorry for bothering you.

**Comment by Andersson007** [comment]
@tangel0v hello, i was going to take a look, so thanks for investigating and closing the issue:)
Yeah, it looked strange as we have integration testing against 10.6.11 IIRC.
Thanks for posting the solution!
